name: Deploy to Azure App Service

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the source code
      - name: Checkout Source
        uses: actions/checkout@v3

      # Step 2: Setup Node.js version
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: SharingPhotoApp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
