name: Deploy to Azure App Service

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the source code
      - name: Checkout Source
        uses: actions/checkout@v3

      # Step 2: Setup Node.js version
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: photosharingapp  # Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Publish profile from secrets
          package: .  # The directory to deploy

      # Step 5: Configure App Settings in Azure
      - name: Azure App Service Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: photosharingapp
          app-settings-json: |
            [
              {
                "name": "MONGO_URI",
                "value": "${{ secrets.MONGO_URI }}",
                "slotSetting": false
              },
              {
                "name": "JWT_SECRET",
                "value": "${{ secrets.JWT_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "PORT",
                "value": "8080",
                "slotSetting": false
              },
              {
                "name": "AZURE_STORAGE_ACCOUNT_NAME",
                "value": "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_STORAGE_ACCOUNT_KEY",
                "value": "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_CONTAINER_NAME",
                "value": "${{ secrets.AZURE_CONTAINER_NAME }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_STORAGE_CONNECTION_STRING",
                "value": "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_BLOB_SAS_TOKEN",
                "value": "${{ secrets.AZURE_BLOB_SAS_TOKEN }}",
                "slotSetting": false
              },
              {
                "name": "WEBSITES_PORT",
                "value": "8080",
                "slotSetting": false
              }
            ]
        id: settings